export const GO_HOME = "G0_HOME"
export const GO_TO_EDITOR = "GO_TO_EDITOR"
export const GO_TO_FOLLOWER = "GO_TO_FOLLOWER"
export const GO_T0_CREATE_PROCESS = "GO_T0_CREATE_PROCESS"
export const ADD_PROCESS = "ADD_PROCESS"
export const ALL_PROCESS = 'ALL_PROCESS'
export const CLEAR_PROCESS = 'CLEAR_PROCESS'
export const FILTERED_PROCESS = "FILTERED_PROCESS"
export const EDIT_STAGE = "EDIT_STAGE"
export const TITLE_STATE = "TITLE_STATE"
export const EDIT_PROCESS = "EDIT_PROCESS"
export const CHANGE = 'CHANGE'
export const EDIT_TITLE = 'EDIT_TITLE'
export const ADD_BACKEND_ACTION = "ADD_BACKEND_ACTION"
export const ADD_ACTION_INFO = 'ADD_ACTION_INFO'
export const EDITING_ACTION = "EDITING_ACTION"
export const EDIT_ACTION = "EDIT_ACTION"


//Follower
export const START_PROCESS_FOLLOWER = "START_PROCESS_FOLLOWER"
export const FILTERED_PROCESS_FOLLOWER = "FILTERED_PROCESS_FOLLOWER"
export const ALL_PROCESS_FOLLOWER ="ALL_PROCESS_FOLLOWER"
export const SUBMIT_STATE = "SUBMIT_STATE"
export const CANCEL_FOLLOWER_PROCESS = "CANCEL_FOLLOWER_PROCESS"
export const TOKEN = "TOKEN"